### ISSUE TITLE
nstudy reports - column titles are all appearing together in first column only

### ISSUE THREAD

**Issue by dtruscot** [philwinne/nstudy_public#121]

**Comment by dtruscot** [comment]
similarly, some of the columns appear to contain different types of information within each column (that is, not all columns contain only the same data type)
for example, in the events.csv folder, my column P contains data about timestamps, object ID, urls, tag names, etc.

**Comment by lfdoherty** [comment]
Make sure you're importing the CSV file with tabs and tabs only as the delimiter.  If the problem is still occurring, email me the affected file(s).
