### ISSUE TITLE
document widget broken in dashboard

### ISSUE THREAD

**Issue by zmarzouk** [philwinne/nstudy_public#16]
once I opened the dashboard, this is all I could see of my document:
![screen shot 2014-07-24 at 1 51 17 pm](https://cloud.githubusercontent.com/assets/5393395/3694635/600f533e-1374-11e4-837b-25eb445df28a.png)

**Comment by zmarzouk** [comment]
hhhhh..is that better :) 

![screen shot 2014-07-24 at 2 03 26 pm](https://cloud.githubusercontent.com/assets/5393395/3694797/fae5100a-1375-11e4-8bac-eed689188d29.png)

**Comment by lfdoherty** [comment]
That is better, but the full window would be better still.

Anyhow, I think this is fixed now.
