### ISSUE TITLE
term definition garbled by pasting from a website

### ISSUE THREAD

**Issue by zmarzouk** [philwinne/nstudy_public#17]
I copied a highlighted sentence from website into the term definition, and then I deleted what I copied. When I tried to type in something new in the definition, it made me write on top of "Definition" and whatever I wrote was highlighted. 
![screen shot 2014-07-24 at 1 56 03 pm](https://cloud.githubusercontent.com/assets/5393395/3694720/3840155e-1375-11e4-8ee1-074235bed679.png)

**Comment by zmarzouk** [comment]
A bigger screen shot :)

![screen shot 2014-07-24 at 2 04 55 pm](https://cloud.githubusercontent.com/assets/5393395/3694811/380620d2-1376-11e4-909b-9ed636ef3b25.png)

**Comment by lfdoherty** [comment]
Fixed as of this moment.
