### ISSUE TITLE
dashboard updates silently stop working after HTML pasted in term definition

### ISSUE THREAD

**Issue by zmarzouk** [philwinne/nstudy_public#19]
I opened the term in a separate tab and made some edits to it, but the same term in the wedge does not show these edits. 

edits in the term in a separate tab: 
![screen shot 2014-07-24 at 2 32 53 pm](https://cloud.githubusercontent.com/assets/5393395/3695118/707d47f2-137a-11e4-8e1f-228538c420de.png)

the term in wedge; 
![screen shot 2014-07-24 at 2 32 40 pm](https://cloud.githubusercontent.com/assets/5393395/3695127/829fb384-137a-11e4-9289-c1751a0e939e.png)

**Comment by zmarzouk** [comment]
I need to make another point: when I close the term tab and reopen it, I see my edits are there but they still do not change in the term widget.

**Comment by lfdoherty** [comment]
What happens if you refresh the dashboard page?

**Comment by zmarzouk** [comment]
it worked,  i refreshed and they synchronized

**Comment by lfdoherty** [comment]
Fixed.
