### ISSUE TITLE
quotes on website do not show on canvas

### ISSUE THREAD

**Issue by zmarzouk** [philwinne/nstudy_public#28]
the quotes I create on the webpage do not show on canvas, and even the webpage I work on does not show as a bookmark at all on my canvas.

**Comment by lfdoherty** [comment]
I can't reproduce this problem.  A few questions:
1. What page were you annotating where you experienced this problem?
2. Did the quotes appear normally in the gutter?
3. When you refresh the page, are the annotations still there?
4. Did refreshing the canvas help?

**Comment by lfdoherty** [comment]
Fixed.
