### ISSUE TITLE
title of documents 

### ISSUE THREAD

**Issue by zmarzouk** [philwinne/nstudy_public#4]
The space allocated for writing the title for the document, does not allow me to write the title.

**Comment by lfdoherty** [comment]
I can't reproduce this - can you provide a screenshot?  What happens when you try to write a title?

**Comment by lfdoherty** [comment]
![screen shot 2014-07-23 at 2 32 06 pm 1](https://cloud.githubusercontent.com/assets/70033/3695502/2947ad5a-137f-11e4-868c-2139085354e8.png)
