### ISSUE TITLE
Highlighting text within the canvas

### ISSUE THREAD

**Issue by dtruscot** [philwinne/nstudy_public#41]
I'm not sure if this is a bug exactly, but when I am in canvas I notice that I am able to highlight text and create additional notes on text that have already been created from another page.  So from highlights etc I've made on the canvas I now have a new set of quotes and notes created in a new "top" group, but this top group has a strange and not very informative title
-> is there a way to change the title of a top group?

**Comment by lfdoherty** [comment]
Should be fixed.
