### ISSUE TITLE
writing notes attached to highlights 

### ISSUE THREAD

**Issue by zmarzouk** [philwinne/nstudy_public#55]
when I am writing the note attached to something I highlighted on the webpage, when I finish the space, the webpage moves up and not the scroll of the note. I have to stand on the note and click to have more space to write. 
![screen shot 2014-10-08 at 12 21 42 pm](https://cloud.githubusercontent.com/assets/5393395/4565522/bea62cb4-4f20-11e4-98a9-094d06060860.png)

**Comment by lfdoherty** [comment]
This seems to be working for me, are you still having problems with this?
