### ISSUE TITLE
when trying to select to create quotes 

### ISSUE THREAD

**Issue by zmarzouk** [philwinne/nstudy_public#58]
When I try and select the part I want to highlight, It does not select the first letter in the word I want but selects the second letter. This always happens when the word is not at the beginning or after a comma. 
the article I am working on where this happens is: 
http://www.sciencedaily.com/releases/2014/08/140804100352.htm

![screen shot 2014-10-08 at 1 03 33 pm](https://cloud.githubusercontent.com/assets/5393395/4566141/3a2805a6-4f26-11e4-953f-95248f6df931.png)

**Comment by lfdoherty** [comment]
I agree that this is strange behaviour, but it's up to Firefox how this works, not nStudy, unfortunately.
