### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by zmarzouk** [philwinne/nstudy_public#6]
I have noticed that the more notes I create on the dash board, the less the space I get to write in  when I open a new note.  

![screen shot 2014-07-23 at 2 51 05 pm](https://cloud.githubusercontent.com/assets/5393395/3680873/98d3e3a4-12b3-11e4-9774-f704bb2fee6f.png)

**Comment by lfdoherty** [comment]
More descriptive error names are generally preferred.

I've fixed this bug (refresh the dashboard to get the fix.)
