### ISSUE TITLE
unable to delete a quote after adding it to multiple new groups

### ISSUE THREAD

**Issue by dtruscot** [philwinne/nstudy_public#61]

**Comment by lfdoherty** [comment]
I can't reproduce this, is it still happening?

**Comment by dtruscot** [comment]
I think this was fixed in an earlier update. Now when I delete a quote after moving it to multiple groups, all occurrences of the quote are deleted by deleting it in just one place.

**Comment by lfdoherty** [comment]
Okay, that's as intended.
