### ISSUE TITLE
Are different highlight colours possible?

### ISSUE THREAD

**Issue by dtruscot** [philwinne/nstudy_public#64]
Or would different highlight colour be too confusing when there is also different colours for notes?

![highlight colours](https://cloud.githubusercontent.com/assets/8264213/4604593/d694fc20-51a9-11e4-954e-14af573ba77a.jpg)

**Comment by lfdoherty** [comment]
I think it's too confusing.  We might use a small number of different colours for differentiating a small set of pre-defined tags at some point.
