### ISSUE TITLE
how can I edit the name of the bookmark? or I cannot in this version? 

### ISSUE THREAD

**Issue by zmarzouk** [philwinne/nstudy_public#70]

**Comment by lfdoherty** [comment]
Just click in the bookmark and type, the text is editable.

**Comment by zmarzouk** [comment]
It's not working, nothing happens when I click it once. When I click twice it opens the bookmark in the maps.

**Comment by lfdoherty** [comment]
Nothing happens when you click, you just start editing the text.

**Comment by zmarzouk** [comment]
I start but nothing happens …it's not editable

**Comment by lfdoherty** [comment]
Screenshot?  I'm not sure what's going on.

**Comment by zmarzouk** [comment]
![screen shot 2014-10-20 at 1 45 08 pm](https://cloud.githubusercontent.com/assets/5393395/4708743/1702351a-589a-11e4-9ce4-c98abc1b7e8d.png)

**Comment by lfdoherty** [comment]
Oh, ic.  Like with the other types, you can only edit them on the map, not
in the side list.

**Comment by zmarzouk** [comment]
yes, only on canvas. and I have to drag the bookmark to the canvas to do that ...

**Comment by lfdoherty** [comment]
correct

**Comment by zmarzouk** [comment]
thank you :)
