### ISSUE TITLE
Lots of tabs open every time I log in

### ISSUE THREAD

**Issue by ilanafle** [philwinne/nstudy_public#71]
each thing I do opens a new tab and when I log in it doesn't take me to the map, it just opens an empty tab. Can we make it so that it takes you to the map as a default or something?

**Comment by lfdoherty** [comment]
I'm not sure what you mean - can you show me a screenshot of what happens when you login?

We could probably open the map by default, yes.

**Comment by ilanafle** [comment]
Hey you fixed it :)
great
