### ISSUE TITLE
No apparent limit to the length of note/document titles on the map

### ISSUE THREAD

**Issue by dtruscot** [philwinne/nstudy_public#91]
Copying/pasting large amounts of text into a document/note title expands the note/document bar length as wide as the entire portion of text (and off the screen in some cases).

On a related note, very long note titles shrink down when you try to edit the note - making it difficult to edit a very long note title (while very long document titles do not shrink, so you can edit them more easily)

**Comment by lfdoherty** [comment]
Both issues fixed.
